# Internal medicine rules

# Clinic-level rules 
clinic_rules:

  clinic_days:
    - Monday
    - Tuesday
    - Wednesday
    - Thursday
    - Friday

  clinic_sessions:
    Monday: [morning, afternoon]
    Tuesday: [morning, afternoon]
    Wednesday: [morning, afternoon]
    Thursday: [afternoon]  
    Friday: [morning, afternoon]

  random_day_off:
    eligible_days: [Monday, Tuesday, Wednesday, Friday]   

  inpatient_schedule:
    inpatient_length: 7
    inpatient_starts_on: Tuesday
    inpatient_ends_on: Monday
    pre_inpatient_leave: Monday     
    post_inpatient_leave: Friday    

  staffing:
    min_providers_per_session: 1
    max_providers_per_session: 5

  holiday_dates:
    - 2025-01-01  # New Year's Day
    - 2025-01-20  # MLK Day
    - 2025-02-17  # Presidents' Day
    - 2025-05-26  # Memorial Day
    - 2025-06-19  # Juneteenth
    - 2025-07-04  # Independence Day
    - 2025-09-01  # Labor Day
    - 2025-10-13  # Indigenous Peoples' Day
    - 2025-11-11  # Veterans Day
    - 2025-11-27  # Thanksgiving
    - 2025-12-25  # Christmas
    - 2026-01-01  # New Year's Day

# Provider-level rules 
providers:
  Bornstein:
    role: MD
    max_clinics_per_week: 4 
    needs_rdo: true

  Mcnett:
    role: MD
    max_clinics_per_week: 9
    needs_rdo: false 

  Mcrae:
    role: PA
    max_clinics_per_week: 6
    needs_rdo: true

  Miles: 
    role: MD
    max_clinics_per_week: 3
    needs_rdo: true
    rdo_preference: Friday
  
  #Orcutt:
  # role: MD
  # max_clinics_per_week: 5
  # needs_rdo: true

  #Rafferty:
  #  role: MD 
  #  max_clinics_per_week: 9
  #  needs_rdo: false
  
  Selig:
    role: NP
    max_clinics_per_week: 6
    needs_rdo: true
  
  Stewart:
    role: MD
    max_clinics_per_week: 4
    needs_rdo: true
  
  Tanay:
    role: NP
    max_clinics_per_week: 6
    needs_rdo: true
  
  Wadlin:
    role: MD
    max_clinics_per_week: 5
    needs_rdo: true