# Internal medicine rules

# Clinic-level rules 
clinic_rules:

  # HARD RULES 
  clinic_days:
    - Monday
    - Tuesday
    - Wednesday
    - Thursday
    - Friday

  clinic_sessions:
    Monday: [morning, afternoon]
    Tuesday: [morning, afternoon]
    Wednesday: [morning, afternoon]
    Thursday: [afternoon]  
    Friday: [morning, afternoon]

  random_day_off:
    enabled: true
    eligible_days: [Monday, Tuesday, Wednesday, Friday]   # Thursday is excluded
    substitute_if_holiday: true                           # If there's a holiday that week, skip assigning an RDO
    substitute_if_leave: true                             # If placed on leave that week, counts as RDO for week 
    override_roles: [NP, PA]                              # NP/PA still get an RDO even if there’s a holiday that week
                                              
  holiday_week_rdo_followup:                              # MD/DO get an RDO the Monday or Friday the week after a holiday 
    enabled: true
    day_options: [Monday, Friday]
    applies_to_roles: [MD, DO]

  inpatient_schedule:
    inpatient_block_length: 7
    inpatient_starts_on: Tuesday
    inpatient_ends_on: Monday
    pre_inpatient_rdo: Monday     # RDO the day before inpatient starts
    post_inpatient_rdo: Friday    # RDO after inpatient ends

  staffing:
    min_providers_per_session: 1
    max_providers_per_session: 4

  holiday_dates:
    - 2025-01-01  # New Year's Day
    - 2025-01-20  # MLK Day
    - 2025-02-17  # Presidents' Day
    - 2025-05-26  # Memorial Day
    - 2025-07-04  # Independence Day
    - 2025-09-01  # Labor Day
    - 2025-11-11  # Veterans Day
    - 2025-11-27  # Thanksgiving
    - 2025-12-25  # Christmas

  # SOFT RULES
  clinic_intensity_limit:
    enabled: true
    enforce_ratio_on_short_weeks: true

# Provider-level rules 
providers:
  Bornstein:
    role: MD
    admin_sessions:
    max_clinics_per_week:
  
  Mccrae:
    role: PA
    admin_sessions: 2
    max_clinics_per_week: 6

  Miles: 
    role: MD
    admin_sessions: 5
    max_clinics_per_week: 3
  
  Orcutt:
    role: MD
    admin_sessions: 3
    max_clinics_per_week: 5
  
  Selig:
    role: NP
    admin_sessions: 2
    max_clinics_per_week: 6
  
  Stewart:
    role: MD
    admin_sessions: 4
    max_clinics_per_week: 4
  
  Tanay:
    role: NP
    admin_sessions: 2
    max_clinics_per_week: 6
  
  Wadlin:
    role: MD
    admin_sessions: 4
    max_clinics_per_week: 4