# Pediatric rules

# Clinic-level rules 
clinic_rules:

  clinic_days:
    - Monday
    - Tuesday
    - Wednesday
    - Thursday
    - Friday

  clinic_sessions:
    Monday: [morning, afternoon]
    Tuesday: [morning, afternoon]
    Wednesday: [morning, afternoon]
    Thursday: [afternoon]  
    Friday: [morning, afternoon]

  random_day_off:
    eligible_days: [Monday, Tuesday, Wednesday, Friday]   # Thursday is excluded

  inpatient_schedule:
    inpatient_length: 7
    inpatient_starts_on: Tuesday
    inpatient_ends_on: Monday
    pre_inpatient_leave: Monday     # RDO the day before inpatient starts
    post_inpatient_leave: Friday    # RDO after inpatient ends

  staffing:
    min_providers_per_session: 1
    max_providers_per_session: 4

  holiday_dates:
    - 2025-01-20  # MLK Day
    - 2025-02-17  # Presidents' Day
    - 2025-05-26  # Memorial Day
    - 2025-06-19  # Juneteenth
    - 2025-07-04  # Independence Day
    - 2025-09-01  # Labor Day
    - 2025-10-13  # Indigenous Peoples' Day
    - 2025-11-11  # Veterans Day
    - 2025-11-27  # Thanksgiving
    - 2025-12-25  # Christmas
    - 2026-01-01  # New Year's Day

# Provider-level rules 
providers:
  Bedele:
    role: MD
    max_clinics_per_week: 6
    needs_rdo: true
    takes_call: true
    max_calls_per_month: null                 
  
  Carrasco:
    role: MD
    max_clinics_per_week: 6
    needs_rdo: true
    takes_call: true
    max_calls_per_month: null   

  Lichtman:
    role: MD
    max_clinics_per_week: 0
    needs_rdo: false
    takes_call: true
    max_calls_per_month: 3      

  Mador: 
    role: MD
    max_clinics_per_week: 6
    needs_rdo: true
    takes_call: true
    max_calls_per_month: null
  
  Menachof:
    role: MD
    max_clinics_per_week: 3
    needs_rdo: true
    takes_call: true
    max_calls_per_month: null

  Miller:
    role: MD
    max_clinics_per_week: 6
    needs_rdo: true
    takes_call: true
    max_calls_per_month: null

  Powell:
    role: MD
    max_clinics_per_week: 0   
    needs_rdo: false          
    fracture_clinic: true     
    takes_call: true     
    max_calls_per_month: 3    

  Shin: 
    role: MD
    max_clinics_per_week: 0
    needs_rdo: false
    takes_call: true           
    max_calls_per_month: 3

  Snyder: 
    role: MD 
    max_clinics_per_week: 9
    needs_rdo: false
    takes_call: false
    max_calls_per_month: null       

  Sridhar: 
    role: MD
    max_clinics_per_week: 6
    needs_rdo: true
    takes_call: true 
    max_calls_per_month: null
  
  #Tarr:
  #  role: MD
  #  max_clinics_per_week: 6
  #  needs_rdo: true
  #  takes_call: true 
  #  max_calls_per_month: null